
# Switches
set_property PACKAGE_PIN V17 [get_ports {A1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A1}]
set_property PACKAGE_PIN V16 [get_ports {A2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A2}]
set_property PACKAGE_PIN W16 [get_ports {B1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B1}]
set_property PACKAGE_PIN W17 [get_ports {B2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B2}]
set_property PACKAGE_PIN W15 [get_ports {C1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {C1}]
set_property PACKAGE_PIN V15 [get_ports {D1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {D1}]
set_property PACKAGE_PIN W14 [get_ports {D2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {D2}]
set_property PACKAGE_PIN W13 [get_ports {E1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {E1}]
set_property PACKAGE_PIN V2 [get_ports {E2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {E2}]
set_property PACKAGE_PIN T3 [get_ports {F1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {F1}]
set_property PACKAGE_PIN T2 [get_ports {F2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {F2}]
set_property PACKAGE_PIN R3 [get_ports {G1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {G1}]
set_property PACKAGE_PIN W2 [get_ports {G2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {G2}]
	
# LEDs
set_property PACKAGE_PIN U16 [get_ports {Ao}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Ao}]
set_property PACKAGE_PIN E19 [get_ports {Bo}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Bo}]
set_property PACKAGE_PIN U19 [get_ports {Co}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Co}]
set_property PACKAGE_PIN V19 [get_ports {Do}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Do}]
set_property PACKAGE_PIN W18 [get_ports {Eo}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Eo}]
set_property PACKAGE_PIN U15 [get_ports {Fo}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Fo}]
set_property PACKAGE_PIN U14 [get_ports {Go}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Go}]
